name = "rocket_demo"

[pg]
address = "postgres://postgres:123456@127.0.0.1:5432/evolve"

[meilisearch]
address = "http://localhost:7700"
api_key = "masterKey"

[redis]
address = "redis://127.0.0.1:6379/"
password = ""
