name = "rocket_demo"

[mysql]
address = "mysql://test:123@127.0.0.1:3306/evolve"

[meilisearch]
address = "http://localhost:7700"
api_key = "masterKey"

[redis]
address = "redis://127.0.0.1:6379/"
password = ""
