[workspace]

members = [
  "./time",
  "./rocket_demo",
  "./clap_demo",
  "./design_pattern",
  "./sql_demo",
  "./redis_demo",
  "./hello_macro",
  "./hello_macro_derive",
  "./leetcode",
  "./logger",
  "./serde_demo",
  "./config"
]
